export const GAME_EVENTS = {
  stateChanged: 'state-changed',
  blockPlaced: 'block-placed',
  roundStarted: 'round-started',
  roundEnded: 'round-ended',
} as const;

export const STORAGE_KEYS = {
  balance: 'neonstack_balance',
  bestHeight: 'neonstack_best_height',
  bet: 'neonstack_bet',
  difficulty: 'neonstack_difficulty',
} as const;

export const NODE_KEYS = {
  canvas: 'Canvas',
  gameLayer: 'GameLayer',
  blocksContainer: 'BlocksContainer',
  swingContainer: 'SwingContainer',
  debrisContainer: 'DebrisContainer',
  particlesContainer: 'ParticlesContainer',
  uiLayer: 'UILayer',
  resultBanner: 'ResultBanner',
} as const;

export const GAME_CONSTANTS = {
  designWidth: 1080,
  designHeight: 1920,
  baseY: -790,
  blockSize: 150,
  swingGapAbove: 460,
  swingSpawnOffsetY: 220,
  swingAmplitudeFraction: 0.18,
  swingRopeLength: 200,
  gravity: 2600,
  baseSwingSpeed: 1.7,
  maxSwingAngleRadians: 0.3,
  cameraFrameFraction: 0.48,
  cameraLerp: 0.09,
  cameraResetLerp: 0.028,
  fallRotationDamping: 0.88,
  collisionAlignmentFraction: 0.9,
  landingSquashDuration: 0.18,
  landingSquashScale: 0.8,
  multiplierPulseScale: 1.25,
  toastLiftY: 20,
  toastScaleFrom: 0.9,
  toastInDuration: 0.12,
  toastHoldDuration: 0.6,
  toastOutDuration: 0.15,
  resultScaleFrom: 0.8,
  resultScaleTo: 1,
  resultScaleEnd: 0.92,
  resultInDuration: 0.2,
  resultHoldDuration: 1.2,
  resultOutDuration: 0.16,
  introSwingDuration: 0.5,
  connectDelayMs: 280,
  resultResetDelayMs: 50,
  resultFallbackDelayMs: 750,
  demolitionFadeDuration: 0.08,
  debrisCount: 8,
  debrisTravelDuration: 0.45,
  debrisVelocityX: 420,
  debrisVelocityYMin: 120,
  debrisVelocityYRange: 420,
  debrisRotationDeltaMax: 200,
  debrisOriginLift: 12,
  particleCount: 12,
  particleRiseDuration: 0.3,
  particleFallDuration: 0.3,
  particleFadeDelay: 0.15,
  particleFadeDuration: 0.45,
  particleVelocityX: 260,
  particleVelocityYMin: 40,
  particleVelocityYRange: 160,
  particleSpreadX: 70,
  particleSpreadY: 20,
  particleDriftFactor: 0.2,
  dustRiseY: 60,
  dustDropY: -24,
  floorToastInterval: 5,
  defaultBalance: 1000,
  defaultBet: 10,
  betStep: 5,
  minBet: 5,
  maxBet: 100,
  ladderVisibleRows: 8,
  fallbackEffectSize: 10,
} as const;
